/* Public website catalogue reference, retrieved 2026-09-24. Not sellable until imported from Square. */
window.TEEBANJ_PREVIEW = [
  {
    id: "preview-100472",
    name: "Men’s Agbada",
    cat: "men",
    price: 350,
    desc: "",
    image: "assets/products/preview-100472.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100466",
    name: "Men’s Bottoms",
    cat: "men",
    price: 80,
    desc: "Elevate your casual style with these bold men’s black-and-white graphic printed bottoms. Featuring intricate tribal-inspired patterns, they pair perfectly with solid tops for a standout look.",
    image: "assets/products/preview-100466.jpg",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100465",
    name: "Men’s Tops",
    cat: "men",
    price: 60,
    desc: "This bold casual shirt showcases vibrant tie-dye accents and a unique African-themed print, ideal for a stylish everyday look or cultural events.",
    image: "assets/products/preview-100465.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100464",
    name: "Men’s Jackets",
    cat: "men",
    price: 120,
    desc: "Upgrade your wardrobe with this sleek men’s jacket, featuring a bold monochrome geometric pattern. Designed with a classic zip-up front and striped cuffs, it effortlessly combines modern style with timeless comfort.",
    image: "assets/products/preview-100464.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100463",
    name: "Aso-oke.",
    cat: "fabrics",
    price: 100,
    desc: "Aso-Oke fabric, a luxurious and versatile traditional Nigerian textile, features vibrant colors with metallic threads woven intricately for a shimmering effect. Perfect for creating statement pieces, elegant attire, and accessories.",
    image: "assets/products/preview-100463.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100462",
    name: "Adire",
    cat: "fabrics",
    price: 60,
    desc: "Elevate your style with this handcrafted Adire fabric. Featuring a captivating mix of rich purple and earthy tones with bold black geometric patterns, this fabric is perfect for creating unique and stylish outfits or home décor.",
    image: "assets/products/preview-100462.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100461",
    name: "Ankra",
    cat: "fabrics",
    price: 70,
    desc: "Ankara fabric: a vibrant, high-quality cotton textile featuring bold, colorful patterns perfect for creating stylish outfits, accessories, and home décor.",
    image: "assets/products/preview-100461.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100460",
    name: "Shoes",
    cat: "accessories",
    price: 100,
    desc: "Step into elegance with these stunning blue sandals featuring crystal-embellished straps, a secure ankle buckle, and a clear block heel for a chic yet comfortable look.",
    image: "assets/products/preview-100460.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100459",
    name: "Asoebi",
    cat: "accessories",
    price: 70,
    desc: "Vibrant Asoebi fabrics in bold, eye-catching colors—perfect for traditional celebrations, weddings, and events. Each piece reflects timeless elegance and cultural pride, crafted to make you stand out.",
    image: "assets/products/preview-100459.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100458",
    name: "Head Ties",
    cat: "accessories",
    price: 150,
    desc: "Elevate your style with these elegant pink head ties, perfect for weddings, cultural events, and celebrations. Intricately designed for a sophisticated look, these head ties add a regal touch to any outfit.",
    image: "assets/products/preview-100458.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100456",
    name: "Women’s Jackets",
    cat: "women",
    price: 70,
    desc: "Elevate your wardrobe with these chic and versatile women’s jackets, perfect for layering. Featuring bold, eye-catching patterns, these jackets effortlessly combine comfort and style, making them ideal for casual and semi-formal occasions.",
    image: "assets/products/preview-100456.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100455",
    name: "Women’s tops",
    cat: "women",
    price: 70,
    desc: "This stylish asymmetrical women’s top features a vibrant yellow and blue floral pattern, perfect for making a bold yet elegant statement. Lightweight and breathable, it pairs beautifully with jeans or formal pants for a versatile look.",
    image: "assets/products/preview-100455.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100454",
    name: "Skirts",
    cat: "women",
    price: 60,
    desc: "Add a vibrant pop of color to your wardrobe with this bold and beautifully patterned skirt. Designed with a flattering fit, it combines comfort with style, perfect for casual outings or special occasions",
    image: "assets/products/preview-100454.jpg",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100325",
    name: "Sego-gele.",
    cat: "fabrics",
    price: 70,
    desc: "The Sego-Gele is a versatile, pre-tied headwrap made from high-quality Sego fabric, perfect for creating stunning, traditional African gele styles with ease. Its structured texture ensures a flawless finish every time, combining convenience and elegance for any special occasion.",
    image: "assets/products/preview-100325.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100324",
    name: "Lace.",
    cat: "fabrics",
    price: 150,
    desc: "Elegant and premium-quality lace fabric in vibrant gold and black hues, featuring intricate embroidery, sequins, and rhinestone embellishments. Perfect for creating eye-catching dresses, gowns, and traditional attires.",
    image: "assets/products/preview-100324.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100323",
    name: "Dresses",
    cat: "women",
    price: 70,
    desc: "",
    image: "assets/products/preview-100323.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100322",
    name: "Women Bottoms",
    cat: "women",
    price: 80,
    desc: "Elevate your style with these bold geometric-patterned women’s pants, featuring a tailored fit and vibrant tones of white, black, and earthy brown. Perfect for casual outings or a polished look with a crisp white blouse.",
    image: "assets/products/preview-100322.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100321",
    name: "Purse",
    cat: "accessories",
    price: 250,
    desc: "Elevate your style with this dazzling black embellished purse and matching heels, adorned with colorful gemstones for a luxurious touch. Perfect for special occasions, these pieces combine elegance with boldness, making them a must-have accessory for a striking statement.",
    image: "assets/products/preview-100321.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100320",
    name: "Sun Glasses",
    cat: "accessories",
    price: 30,
    desc: "Classic black polarized aviator sunglasses offering optimal UV protection with a sleek metal frame.",
    image: "assets/products/preview-100320.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
  {
    id: "preview-100317",
    name: "Men Caps",
    cat: "men",
    price: 50,
    desc: "Stylish and unique men’s traditional caps available in vibrant colors like navy with orange, royal blue, and purple with patterns. Perfect for adding a touch of sophistication to cultural or formal attire.",
    image: "assets/products/preview-100317.webp",
    variation: "Contact us for sizes and colours",
    stock: 0,
    colors: ["#222222"],
    rating: 0,
    reviews: 0,
    tags: [],
    preview: true,
  },
];
