SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS products (
 id VARCHAR(192) PRIMARY KEY,
 square_item_id VARCHAR(192) NOT NULL,
 name VARCHAR(500) NOT NULL,
 description TEXT NOT NULL,
 category VARCHAR(64) NOT NULL DEFAULT 'fabrics',
 variation_name VARCHAR(255) NOT NULL,
 sku VARCHAR(255) NOT NULL DEFAULT '',
 price_cents BIGINT UNSIGNED NOT NULL,
 image_url TEXT NOT NULL,
 stock DECIMAL(16,5) NOT NULL DEFAULT 0,
 active BOOLEAN NOT NULL DEFAULT 1,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS customers (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS orders (
 id CHAR(32) PRIMARY KEY,
 session_owner CHAR(64) NOT NULL,
 customer_id BIGINT UNSIGNED NULL,
 request_hash CHAR(64) NOT NULL,
 customer_json JSON NOT NULL,
 square_request JSON NOT NULL,
 square_order_id VARCHAR(192) NULL UNIQUE,
 payment_link_id VARCHAR(192) NULL,
 checkout_url TEXT NULL,
 status VARCHAR(32) NOT NULL DEFAULT 'pending',
 total_cents BIGINT UNSIGNED NULL,
 payment_id VARCHAR(192) NULL UNIQUE,
 receipt_url TEXT NULL,
 tracking VARCHAR(500) NOT NULL DEFAULT '',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(customer_id), INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_items (
 order_id CHAR(32) NOT NULL,
 product_id VARCHAR(192) NOT NULL,
 name VARCHAR(500) NOT NULL,
 quantity INT UNSIGNED NOT NULL,
 price_cents BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(order_id,product_id),
 FOREIGN KEY(order_id) REFERENCES orders(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS webhook_events (
 id VARCHAR(192) PRIMARY KEY,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(254) NOT NULL,
 subject VARCHAR(200) NOT NULL,
 message TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS subscribers (email VARCHAR(254) PRIMARY KEY,consent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rate_limits (bucket CHAR(64) PRIMARY KEY,attempts INT NOT NULL DEFAULT 0,expires_at BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
